<?xml version="1.0" encoding="utf-8"?><Database Name="kasa" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-BG1SF22R\SQLEXPRESS;Initial Catalog=kasa;Integrated Security=True" SettingsObjectName="kassasysteem.Properties.Settings" SettingsPropertyName="kasaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[ORDER]" Member="ORDERs">
    <Type Name="ORDER">
      <Column Name="orderid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="customerid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ORDER_item" Member="items" ThisKey="orderid" OtherKey="orderid" Type="item" />
      <Association Name="CUSTOMER_ORDER" Member="CUSTOMER" ThisKey="customerid" OtherKey="customerid" Type="CUSTOMER" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CUSTOMER" Member="CUSTOMERs">
    <Type Name="CUSTOMER">
      <Column Name="customerid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="lastname" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="city" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="phonenumber" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="CUSTOMER_ORDER" Member="ORDERs" ThisKey="customerid" OtherKey="customerid" Type="ORDER" />
    </Type>
  </Table>
  <Table Name="dbo.item" Member="items">
    <Type Name="item">
      <Column Name="itemid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="amount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="orderid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="productid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ORDER_item" Member="ORDER" ThisKey="orderid" OtherKey="orderid" Type="ORDER" IsForeignKey="true" />
      <Association Name="PRODUCT_item" Member="PRODUCT" ThisKey="productid" OtherKey="productid" Type="PRODUCT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PRODUCT" Member="PRODUCTs">
    <Type Name="PRODUCT">
      <Column Name="productid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="productnaam" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="prijs" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="productypeid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PRODUCT_item" Member="items" ThisKey="productid" OtherKey="productid" Type="item" />
      <Association Name="PRODUCTYPE_PRODUCT" Member="PRODUCTYPE" ThisKey="productypeid" OtherKey="productypeid" Type="PRODUCTYPE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PRODUCTYPE" Member="PRODUCTYPEs">
    <Type Name="PRODUCTYPE">
      <Column Name="productypeid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="omschijving" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="PRODUCTYPE_PRODUCT" Member="PRODUCTs" ThisKey="productypeid" OtherKey="productypeid" Type="PRODUCT" />
    </Type>
  </Table>
</Database>